[program:laravel-octane]
process_name=%(program_name)s_%(process_num)02d
command=php /home/lms/lms-comics-2/lms-comics/artisan octane:start --server=frankenphp --host=0.0.0.0 --port=8000
autostart=true
autorestart=true
user=lms
redirect_stderr=true
stdout_logfile=/home/lms/lms-comics-2/lms-comics/storage/logs/octane.log

[program:laravel-horizon]
process_name=%(program_name)s
command=php /home/lms/lms-comics-2/lms-comics/artisan horizon
autostart=true
autorestart=true
user=lms
redirect_stderr=true
stdout_logfile=/home/lms/lms-comics-2/lms-comics/storage/logs/horizon.log
stopwaitsecs=3600

[program:laravel-reverb]
process_name=%(program_name)s_%(process_num)02d
command=php /home/lms/lms-comics-2/lms-comics/artisan reverb:start
autostart=true
autorestart=true
user=lms
redirect_stderr=true
stdout_logfile=/home/lms/lms-comics-2/lms-comics/storage/logs/reverb.log
